// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Block struct {
	ID            string     `json:"_id"`
	Header        *Identity  `json:"header"`
	Size          *int       `json:"size"`
	Hash          *string    `json:"hash"`
	Version       *int       `json:"version"`
	Prevhash      *string    `json:"prevhash"`
	Merkelroot    *string    `json:"merkelroot"`
	Timestamp     *int       `json:"timestamp"`
	Index         *int       `json:"index"`
	Primary       *int       `json:"primary"`
	NestConsensus *string    `json:"nestConsensus"`
	Witnesses     []*Witness `json:"witnesses"`
}

type Identity struct {
	ID string `json:"ID"`
}

type Witness struct {
	Invocation   *string `json:"invocation"`
	Verification *string `json:"verification"`
}
